#!/bin/bash

# git-asc
# --------------
# Description: This command can git add, git status, git commit.
# Created at : 2026.07.04
# Updated at : 2026.07.04

git-asc() {
  git add .
  git status

  echo -n 'are you sure want to commit? [Y/n]: '
  read ANS

  case $ANS in
    [Yy]* )
      ;;
    [Nn]* )
      echo 'commit was not created'
      git restore --staged .
      return 1
      ;;
    * )
      echo 'looks not found answer'
      echo 'commit was not created'
      git restore --staged .
      return 1
      ;;
  esac

  echo -n 'enter commit message: '
  read commit_msg

  if [ -z "$commit_msg" ]; then
    echo 'no inputs'
    echo 'commit was not created'
    git restore --staged .
    return 1
  fi

  git commit -m "$commit_msg"

  echo '\n'
  echo 'git commit was created:'
  echo $(git log --oneline | head -n 1)
}
