#!/bin/zsh

# mkdircd
# --------------
# Description: This command can quickly create folder and quickly move created folder
# Created at : 2025.05.13
# Updated at : 2026.06.10

mkdircd() {
    text="$1"
    mkdir -p $1
    cd $1
}
