#!/bin/bash

# nix-switch
# --------------
# Description: This command can apply nix configuration quickly
# Created at : 2026.07.04
# Updated at : 2026.07.04

nix-switch() {
  sudo nixos-rebuild switch --flake /home/sora81dev/dotfiles#hp-notebook --show-trace --verbose
}
