#!/bin/bash

# nix-switch
# --------------
# Description: This command can test nix configuration quickly
# Created at : 2026.09.08
# Updated at : 2026.09.08

nix-switch() {
  nixos-rebuild test --flake /home/sora81dev/dotfiles#hp-notebook --show-trace --verbose
}
