gui:
  authorColors:
    'sora81dev': '#61a6c6'

  branchColorPatterns:
    '^main$'  : '#43a08e'
    '^fix/'   : '#e8439d'
    '^style/' : '#b95dcc'
    '^hotfilx': '#ff0000'
    '^feat/'  : '#26d11d'

  customIcons:
    extensions:
      "*":
        color: "#aaaaaa"

      ".env":
        color: "#ff0000"

  theme:
    activeBorderColor:
      - "#61a6c6"
      - bold

    optionsTextColor:
      - "#61a6cb"

    selectedLineBgColor:
      - "#c0c0c0"

    nerdFontsVersion: "2"

    showFileIcons: true

git:
  papers:
    - colorArg: always
      pager: delta --paging=never --side-by-side
